### ISSUE TITLE
Get detected randomly and instantly with no ai detection

### ISSUE THREAD

**Issue by FalcoGer** [GABRlEL/payday2.pw-Mods#1]
Sometimes, seemingly at random, cameras and AI detect me, corpses or bags. The `?` doesn't show, it instantly goes to `!`.

**Comment by GABRlEL** [comment]
Hey, I updated and improved the mod. Please check if the issue is still there.

**Comment by GABRlEL** [comment]
Will close the issue as I tested the mod myself. Feel free to contact me again, if you need more help.
