### ISSUE TITLE
Always 3 concealment only change the number not the detection risk

### ISSUE THREAD

**Issue by Rrhyast** [GABRlEL/payday2.pw-Mods#4]

**Comment by GABRlEL** [comment]
Hey Rrhyast, thank you for your comment. Did you try this as client or as host?

**Comment by Rrhyast** [comment]
> Hey Rrhyast, thank you for your issue. Did you try this as client or as host?

client side

**Comment by GABRlEL** [comment]
This mod only works as a host, I can't fix this unfortunately.
